from collections import namedtuple

from django.test import TestCase
from ninja.testing import TestClient

from magnificence.api.views import router as app_router
from magnificence.services import populate_data

TestDatum = namedtuple("TestDatum", ["team_short_name", "expected_data"])


class AppTestCase(TestCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        populate_data()

    def test_magnificent_team_api(self):
        client = TestClient(app_router)
        response = client.get("/magnificent-team")

        self.assertEqual(response.status_code, 200)
        self.assertEqual(
            response.json(),
            [
                {
                    "element_type": {
                        "singular_name": "Goalkeeper",
                        "singular_name_short": "GKP",
                    },
                    "first_name": "Mark",
                    "second_name": "Flekken",
                    "team": {
                        "code": 94,
                        "name": "Brentford",
                        "short_name": "BRE",
                    },
                    "goals_scored": 0,
                    "assists": 0,
                    "goals_conceded": 15,
                    "penalties_saved": 0,
                    "penalties_missed": 0,
                    "saves": 42,
                    "web_name": "Flekken",
                    "total_points": 23,
                    "chance_of_playing_this_round": None,
                    "chance_of_playing_next_round": None,
                },
                {
                    "element_type": {
                        "singular_name": "Defender",
                        "singular_name_short": "DEF",
                    },
                    "first_name": "Nathan",
                    "second_name": "Collins",
                    "team": {
                        "code": 94,
                        "name": "Brentford",
                        "short_name": "BRE",
                    },
                    "goals_scored": 1,
                    "assists": 3,
                    "goals_conceded": 15,
                    "penalties_saved": 0,
                    "penalties_missed": 0,
                    "saves": 0,
                    "web_name": "Collins",
                    "total_points": 26,
                    "chance_of_playing_this_round": None,
                    "chance_of_playing_next_round": None,
                },
                {
                    "element_type": {
                        "singular_name": "Defender",
                        "singular_name_short": "DEF",
                    },
                    "first_name": "Rayan",
                    "second_name": "Aït-Nouri",
                    "team": {"code": 39, "name": "Wolves", "short_name": "WOL"},
                    "goals_scored": 2,
                    "assists": 2,
                    "goals_conceded": 22,
                    "penalties_saved": 0,
                    "penalties_missed": 0,
                    "saves": 0,
                    "web_name": "Aït-Nouri",
                    "total_points": 23,
                    "chance_of_playing_this_round": 100,
                    "chance_of_playing_next_round": 100,
                },
                {
                    "element_type": {
                        "singular_name": "Midfielder",
                        "singular_name_short": "MID",
                    },
                    "first_name": "Bukayo",
                    "second_name": "Saka",
                    "team": {"code": 3, "name": "Arsenal", "short_name": "ARS"},
                    "goals_scored": 2,
                    "assists": 7,
                    "goals_conceded": 5,
                    "penalties_saved": 0,
                    "penalties_missed": 0,
                    "saves": 0,
                    "web_name": "Saka",
                    "total_points": 54,
                    "chance_of_playing_this_round": 75,
                    "chance_of_playing_next_round": 75,
                },
                {
                    "element_type": {
                        "singular_name": "Midfielder",
                        "singular_name_short": "MID",
                    },
                    "first_name": "Cole",
                    "second_name": "Palmer",
                    "team": {"code": 8, "name": "Chelsea", "short_name": "CHE"},
                    "goals_scored": 6,
                    "assists": 5,
                    "goals_conceded": 10,
                    "penalties_saved": 0,
                    "penalties_missed": 0,
                    "saves": 0,
                    "web_name": "Palmer",
                    "total_points": 69,
                    "chance_of_playing_this_round": 100,
                    "chance_of_playing_next_round": 100,
                },
                {
                    "element_type": {
                        "singular_name": "Midfielder",
                        "singular_name_short": "MID",
                    },
                    "first_name": "Mohamed",
                    "second_name": "Salah",
                    "team": {
                        "code": 14,
                        "name": "Liverpool",
                        "short_name": "LIV",
                    },
                    "goals_scored": 5,
                    "assists": 5,
                    "goals_conceded": 3,
                    "penalties_saved": 0,
                    "penalties_missed": 0,
                    "saves": 0,
                    "web_name": "M.Salah",
                    "total_points": 74,
                    "chance_of_playing_this_round": None,
                    "chance_of_playing_next_round": None,
                },
                {
                    "element_type": {
                        "singular_name": "Forward",
                        "singular_name_short": "FWD",
                    },
                    "first_name": "Erling",
                    "second_name": "Haaland",
                    "team": {
                        "code": 43,
                        "name": "Man City",
                        "short_name": "MCI",
                    },
                    "goals_scored": 10,
                    "assists": 0,
                    "goals_conceded": 9,
                    "penalties_saved": 0,
                    "penalties_missed": 0,
                    "saves": 0,
                    "web_name": "Haaland",
                    "total_points": 69,
                    "chance_of_playing_this_round": 100,
                    "chance_of_playing_next_round": 100,
                },
            ],
        )

    def test_magnificent_team_api__filtered_by_team(self):
        client = TestClient(app_router)

        test_data = [
            TestDatum(
                "ARS",
                [
                    {
                        "element_type": {
                            "singular_name": "Goalkeeper",
                            "singular_name_short": "GKP",
                        },
                        "first_name": "David",
                        "second_name": "Raya Martin",
                        "team": {
                            "code": 3,
                            "name": "Arsenal",
                            "short_name": "ARS",
                        },
                        "goals_scored": 0,
                        "assists": 0,
                        "goals_conceded": 8,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 27,
                        "web_name": "Raya",
                        "total_points": 37,
                        "chance_of_playing_this_round": 100,
                        "chance_of_playing_next_round": 100,
                    },
                    {
                        "element_type": {
                            "singular_name": "Defender",
                            "singular_name_short": "DEF",
                        },
                        "first_name": "Gabriel",
                        "second_name": "dos Santos Magalhães",
                        "team": {
                            "code": 3,
                            "name": "Arsenal",
                            "short_name": "ARS",
                        },
                        "goals_scored": 2,
                        "assists": 0,
                        "goals_conceded": 8,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 0,
                        "web_name": "Gabriel",
                        "total_points": 40,
                        "chance_of_playing_this_round": None,
                        "chance_of_playing_next_round": None,
                    },
                    {
                        "element_type": {
                            "singular_name": "Defender",
                            "singular_name_short": "DEF",
                        },
                        "first_name": "Jurriën",
                        "second_name": "Timber",
                        "team": {
                            "code": 3,
                            "name": "Arsenal",
                            "short_name": "ARS",
                        },
                        "goals_scored": 0,
                        "assists": 1,
                        "goals_conceded": 4,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 0,
                        "web_name": "J.Timber",
                        "total_points": 19,
                        "chance_of_playing_this_round": 75,
                        "chance_of_playing_next_round": 75,
                    },
                    {
                        "element_type": {
                            "singular_name": "Midfielder",
                            "singular_name_short": "MID",
                        },
                        "first_name": "Gabriel",
                        "second_name": "Martinelli Silva",
                        "team": {
                            "code": 3,
                            "name": "Arsenal",
                            "short_name": "ARS",
                        },
                        "goals_scored": 2,
                        "assists": 2,
                        "goals_conceded": 5,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 0,
                        "web_name": "Martinelli",
                        "total_points": 35,
                        "chance_of_playing_this_round": 75,
                        "chance_of_playing_next_round": 100,
                    },
                    {
                        "element_type": {
                            "singular_name": "Midfielder",
                            "singular_name_short": "MID",
                        },
                        "first_name": "Bukayo",
                        "second_name": "Saka",
                        "team": {
                            "code": 3,
                            "name": "Arsenal",
                            "short_name": "ARS",
                        },
                        "goals_scored": 2,
                        "assists": 7,
                        "goals_conceded": 5,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 0,
                        "web_name": "Saka",
                        "total_points": 54,
                        "chance_of_playing_this_round": 75,
                        "chance_of_playing_next_round": 75,
                    },
                    {
                        "element_type": {
                            "singular_name": "Midfielder",
                            "singular_name_short": "MID",
                        },
                        "first_name": "Leandro",
                        "second_name": "Trossard",
                        "team": {
                            "code": 3,
                            "name": "Arsenal",
                            "short_name": "ARS",
                        },
                        "goals_scored": 2,
                        "assists": 1,
                        "goals_conceded": 5,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 0,
                        "web_name": "Trossard",
                        "total_points": 26,
                        "chance_of_playing_this_round": None,
                        "chance_of_playing_next_round": None,
                    },
                    {
                        "element_type": {
                            "singular_name": "Forward",
                            "singular_name_short": "FWD",
                        },
                        "first_name": "Kai",
                        "second_name": "Havertz",
                        "team": {
                            "code": 3,
                            "name": "Arsenal",
                            "short_name": "ARS",
                        },
                        "goals_scored": 4,
                        "assists": 1,
                        "goals_conceded": 8,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 0,
                        "web_name": "Havertz",
                        "total_points": 42,
                        "chance_of_playing_this_round": 75,
                        "chance_of_playing_next_round": 100,
                    },
                ],
            ),
            TestDatum(
                "wol",
                [
                    {
                        "element_type": {
                            "singular_name": "Goalkeeper",
                            "singular_name_short": "GKP",
                        },
                        "first_name": "Sam",
                        "second_name": "Johnstone",
                        "team": {
                            "code": 39,
                            "name": "Wolves",
                            "short_name": "WOL",
                        },
                        "goals_scored": 0,
                        "assists": 0,
                        "goals_conceded": 13,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 19,
                        "web_name": "Johnstone",
                        "total_points": 10,
                        "chance_of_playing_this_round": None,
                        "chance_of_playing_next_round": 75,
                    },
                    {
                        "element_type": {
                            "singular_name": "Defender",
                            "singular_name_short": "DEF",
                        },
                        "first_name": "Rayan",
                        "second_name": "Aït-Nouri",
                        "team": {
                            "code": 39,
                            "name": "Wolves",
                            "short_name": "WOL",
                        },
                        "goals_scored": 2,
                        "assists": 2,
                        "goals_conceded": 22,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 0,
                        "web_name": "Aït-Nouri",
                        "total_points": 23,
                        "chance_of_playing_this_round": 100,
                        "chance_of_playing_next_round": 100,
                    },
                    {
                        "element_type": {
                            "singular_name": "Defender",
                            "singular_name_short": "DEF",
                        },
                        "first_name": "Nélson",
                        "second_name": "Cabral Semedo",
                        "team": {
                            "code": 39,
                            "name": "Wolves",
                            "short_name": "WOL",
                        },
                        "goals_scored": 0,
                        "assists": 2,
                        "goals_conceded": 14,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 0,
                        "web_name": "N.Semedo",
                        "total_points": 9,
                        "chance_of_playing_this_round": 100,
                        "chance_of_playing_next_round": 100,
                    },
                    {
                        "element_type": {
                            "singular_name": "Midfielder",
                            "singular_name_short": "MID",
                        },
                        "first_name": "Boubacar",
                        "second_name": "Traoré",
                        "team": {
                            "code": 39,
                            "name": "Wolves",
                            "short_name": "WOL",
                        },
                        "goals_scored": 0,
                        "assists": 0,
                        "goals_conceded": 0,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 0,
                        "web_name": "B.Traore",
                        "total_points": 0,
                        "chance_of_playing_this_round": 0,
                        "chance_of_playing_next_round": 0,
                    },
                    {
                        "element_type": {
                            "singular_name": "Midfielder",
                            "singular_name_short": "MID",
                        },
                        "first_name": "Jean-Ricner",
                        "second_name": "Bellegarde",
                        "team": {
                            "code": 39,
                            "name": "Wolves",
                            "short_name": "WOL",
                        },
                        "goals_scored": 1,
                        "assists": 1,
                        "goals_conceded": 10,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 0,
                        "web_name": "Bellegarde",
                        "total_points": 21,
                        "chance_of_playing_this_round": None,
                        "chance_of_playing_next_round": None,
                    },
                    {
                        "element_type": {
                            "singular_name": "Midfielder",
                            "singular_name_short": "MID",
                        },
                        "first_name": "Mario",
                        "second_name": "Lemina",
                        "team": {
                            "code": 39,
                            "name": "Wolves",
                            "short_name": "WOL",
                        },
                        "goals_scored": 1,
                        "assists": 1,
                        "goals_conceded": 23,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 0,
                        "web_name": "Mario Jr.",
                        "total_points": 26,
                        "chance_of_playing_this_round": 100,
                        "chance_of_playing_next_round": 100,
                    },
                    {
                        "element_type": {
                            "singular_name": "Forward",
                            "singular_name_short": "FWD",
                        },
                        "first_name": "Jørgen",
                        "second_name": "Strand Larsen",
                        "team": {
                            "code": 39,
                            "name": "Wolves",
                            "short_name": "WOL",
                        },
                        "goals_scored": 3,
                        "assists": 1,
                        "goals_conceded": 19,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 0,
                        "web_name": "Strand Larsen",
                        "total_points": 34,
                        "chance_of_playing_this_round": None,
                        "chance_of_playing_next_round": None,
                    },
                ],
            ),
            TestDatum(
                "avl",
                [
                    {
                        "element_type": {
                            "singular_name": "Goalkeeper",
                            "singular_name_short": "GKP",
                        },
                        "first_name": "Emiliano",
                        "second_name": "Martínez Romero",
                        "team": {
                            "code": 7,
                            "name": "Aston Villa",
                            "short_name": "AVL",
                        },
                        "goals_scored": 0,
                        "assists": 0,
                        "goals_conceded": 10,
                        "penalties_saved": 1,
                        "penalties_missed": 0,
                        "saves": 20,
                        "web_name": "Martinez",
                        "total_points": 28,
                        "chance_of_playing_this_round": None,
                        "chance_of_playing_next_round": None,
                    },
                    {
                        "element_type": {
                            "singular_name": "Defender",
                            "singular_name_short": "DEF",
                        },
                        "first_name": "Lucas",
                        "second_name": "Digne",
                        "team": {
                            "code": 7,
                            "name": "Aston Villa",
                            "short_name": "AVL",
                        },
                        "goals_scored": 0,
                        "assists": 3,
                        "goals_conceded": 9,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 0,
                        "web_name": "Digne",
                        "total_points": 28,
                        "chance_of_playing_this_round": None,
                        "chance_of_playing_next_round": None,
                    },
                    {
                        "element_type": {
                            "singular_name": "Defender",
                            "singular_name_short": "DEF",
                        },
                        "first_name": "Ezri",
                        "second_name": "Konsa Ngoyo",
                        "team": {
                            "code": 7,
                            "name": "Aston Villa",
                            "short_name": "AVL",
                        },
                        "goals_scored": 1,
                        "assists": 0,
                        "goals_conceded": 9,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 0,
                        "web_name": "Konsa",
                        "total_points": 17,
                        "chance_of_playing_this_round": 100,
                        "chance_of_playing_next_round": 100,
                    },
                    {
                        "element_type": {
                            "singular_name": "Midfielder",
                            "singular_name_short": "MID",
                        },
                        "first_name": "Jacob",
                        "second_name": "Ramsey",
                        "team": {
                            "code": 7,
                            "name": "Aston Villa",
                            "short_name": "AVL",
                        },
                        "goals_scored": 0,
                        "assists": 2,
                        "goals_conceded": 9,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 0,
                        "web_name": "Ramsey",
                        "total_points": 18,
                        "chance_of_playing_this_round": 100,
                        "chance_of_playing_next_round": 100,
                    },
                    {
                        "element_type": {
                            "singular_name": "Midfielder",
                            "singular_name_short": "MID",
                        },
                        "first_name": "Morgan",
                        "second_name": "Rogers",
                        "team": {
                            "code": 7,
                            "name": "Aston Villa",
                            "short_name": "AVL",
                        },
                        "goals_scored": 2,
                        "assists": 2,
                        "goals_conceded": 9,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 0,
                        "web_name": "Rogers",
                        "total_points": 34,
                        "chance_of_playing_this_round": None,
                        "chance_of_playing_next_round": None,
                    },
                    {
                        "element_type": {
                            "singular_name": "Midfielder",
                            "singular_name_short": "MID",
                        },
                        "first_name": "Youri",
                        "second_name": "Tielemans",
                        "team": {
                            "code": 7,
                            "name": "Aston Villa",
                            "short_name": "AVL",
                        },
                        "goals_scored": 0,
                        "assists": 3,
                        "goals_conceded": 10,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 0,
                        "web_name": "Tielemans",
                        "total_points": 30,
                        "chance_of_playing_this_round": None,
                        "chance_of_playing_next_round": None,
                    },
                    {
                        "element_type": {
                            "singular_name": "Forward",
                            "singular_name_short": "FWD",
                        },
                        "first_name": "Ollie",
                        "second_name": "Watkins",
                        "team": {
                            "code": 7,
                            "name": "Aston Villa",
                            "short_name": "AVL",
                        },
                        "goals_scored": 5,
                        "assists": 2,
                        "goals_conceded": 7,
                        "penalties_saved": 0,
                        "penalties_missed": 0,
                        "saves": 0,
                        "web_name": "Watkins",
                        "total_points": 49,
                        "chance_of_playing_this_round": 100,
                        "chance_of_playing_next_round": 100,
                    },
                ],
            ),
        ]

        for test_datum in test_data:
            with self.subTest(team_short_name=test_datum.team_short_name):
                response = client.get(
                    f"/magnificent-team?team_short_name={test_datum.team_short_name}"
                )
                self.assertEqual(response.status_code, 200)
                self.assertEqual(
                    response.json(),
                    test_datum.expected_data,
                )
