# Generated by Django 5.1.2 on 2024-10-24 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElementType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("singular_name", models.CharField(max_length=255)),
                (
                    "singular_name_short",
                    models.CharField(
                        choices=[
                            ("GKP", "Goalkeeper"),
                            ("DEF", "Sub Defender"),
                            ("MID", "Midfielder"),
                            ("FWD", "Forward"),
                        ],
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chance_of_playing_next_round",
                    models.IntegerField(null=True),
                ),
                (
                    "chance_of_playing_this_round",
                    models.IntegerField(null=True),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("second_name", models.CharField(max_length=255)),
                ("web_name", models.CharField(max_length=255)),
                ("total_points", models.IntegerField()),
                ("goals_scored", models.IntegerField()),
                ("assists", models.IntegerField()),
                ("goals_conceded", models.IntegerField()),
                ("penalties_saved", models.IntegerField()),
                ("penalties_missed", models.IntegerField()),
                ("saves", models.IntegerField()),
                (
                    "element_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="magnificence.elementtype",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="magnificence.team",
                    ),
                ),
            ],
        ),
    ]
